### ISSUE TITLE
Bump kernel

### ISSUE THREAD

**Issue by zewelor** [BlueKrypto/k3os-kernel#4]
Hi

is it possible to update kernel to newest 5.15.0-73.80 and release new k3os version with this kernel ?

**Comment by BlueKrypto** [comment]
Yes, I was just thinking that I needed to bump the kernel. I will add this to my todo list.

**Comment by BlueKrypto** [comment]
@zewelor I have release the k3OS release candidate [v0.24.15-k3s1-rc0](https://github.com/BlueKrypto/k3os/releases/tag/v0.24.15-k3s1-rc0) which bumps the k3s version to v0.24.15-k3s1-rc0 and the kernel version to [5.15.0-76.83](https://github.com/BlueKrypto/k3os-kernel/releases/download/5.15.0-76.83-bluekrypto1) as these are the only changes for this release they should be stable, but I still have some testing to do before I set it as a non pre-release.

**Comment by zewelor** [comment]
Great thanks !

EDIT:
Also thanks you so much for maintaining k3os. Are you planning to move eventually to 1.25 also ?

**Comment by BlueKrypto** [comment]
@zewelor just wanted to update you and let you know that the completed and tested release has been tagged.

I do plan to update to 1.25, I am currently assessing the viability of maintaining multiple streams / figuring out how I could possibly keep 1.24, 1.25, 1.26 and possible 1.27 all at the same time. We will see what I come up with.

Your welcome, I have been using it for a long time and liked the way it was designed while having most of the skills needed so I figured I should step up since I didn't see anyone else doing so.
